In [2]:
import numpy as np

In [3]:
np.set_printoptions(suppress = True,linewidth = 100, precision = 2)

In [4]:
Loan_data_raw = np.genfromtxt('loan-data.csv', delimiter = ';', autostrip = True)

In [5]:
Loan_data_raw

array([[        nan,         nan,         nan, ...,         nan,         nan,         nan],
       [48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [6]:
np.isnan(Loan_data_raw).sum()

88019

In [7]:
temporary_fill = np.nanmax(Loan_data_raw)+1
temporary_mean = np.nanmean(Loan_data_raw, axis = 0)

C:\Users\Admin\AppData\Local\Temp\ipykernel_9236\3538041537.py:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(Loan_data_raw, axis = 0)


In [8]:
temporary_fill

68616520.0

In [9]:
temporary_stats = np.array([np.nanmin(Loan_data_raw, axis = 0),
                          temporary_mean,
                          np.nanmax(Loan_data_raw, axis = 0)])

C:\Users\Admin\AppData\Local\Temp\ipykernel_9236\1015254649.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(Loan_data_raw, axis = 0),
C:\Users\Admin\AppData\Local\Temp\ipykernel_9236\1015254649.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(Loan_data_raw, axis = 0)])


In [10]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [11]:
column_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [12]:
column_numeric = np.argwhere(np.isnan(temporary_mean)== False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [13]:
Loan_data_string = np.genfromtxt('loan-data.csv',
                                 delimiter = ';', 
                                 skip_header = 1, 
                                 autostrip = True, 
                                 usecols= column_strings, 
                                 dtype = np.str)

C:\Users\Admin\AppData\Local\Temp\ipykernel_9236\2375632347.py:6: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


In [14]:
Loan_data_string

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [15]:
Loan_data_numeric = np.genfromtxt('loan-data.csv',
                                 delimiter = ';', 
                                 skip_header = 1, 
                                 autostrip = True, 
                                 usecols= column_numeric, 
                                 filling_values = temporary_fill)
Loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [16]:
header_full = np.genfromtxt("loan-data.csv", 
                              delimiter = ';',
                              autostrip = True,
                              dtype = np.str_,
                              max_rows = 1)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [17]:
head_strings,head_numeric = header_full[column_strings], header_full[column_numeric]

In [18]:
head_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [19]:
head_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [20]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [21]:
checkpoint_test = checkpoint("checkpoint_test", head_strings, Loan_data_string)

In [22]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [23]:
np.array_equal(checkpoint_test['data'], Loan_data_string)

True

In [24]:
head_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [25]:
head_strings[0]

'issue_d'

In [26]:
Loan_data_string

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [27]:
Loan_data_string[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [28]:
np.unique(Loan_data_string[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [29]:
Loan_data_string[:,0] = np.chararray.strip(Loan_data_string[:,0], "-15")

In [30]:
np.unique(Loan_data_string[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [31]:
months = np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])

In [32]:
for i in  range(13):
    Loan_data_string[:,0] = np.where(Loan_data_string[:,0] == months[i],
                                    i,
                                    Loan_data_string[:,0])

In [33]:
np.unique(Loan_data_string[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [34]:
head_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [35]:
np.unique(Loan_data_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [36]:
np.unique(Loan_data_string[:,1]).size


9

In [37]:
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (16-30 days)'])

In [38]:
Loan_data_string[:,1] = np.where(np.isin(Loan_data_string[:,1], status_bad),0,1)

In [39]:
np.unique(Loan_data_string[:,1])

array(['0', '1'], dtype='<U69')

In [40]:
head_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [41]:
Loan_data_string[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [42]:
np.unique(Loan_data_string[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [43]:
Loan_data_string[:,2] = np.chararray.strip(Loan_data_string[:,2], "months")
Loan_data_string[:,2]

array(['36 ', '36 ', '36 ', ..., '36 ', '36 ', '36 '], dtype='<U69')

In [44]:
head_strings[2] = "term_months"

In [45]:
Loan_data_string[:,2] = np.where(Loan_data_string[:,2] == '',
                                '60',
                                Loan_data_string[:,2])
Loan_data_string[:,2]

array(['36 ', '36 ', '36 ', ..., '36 ', '36 ', '36 '], dtype='<U69')

In [46]:
np.unique(Loan_data_string[:,2])

array(['36 ', '60', '60 '], dtype='<U69')

In [47]:
head_strings

array(['issue_d', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [48]:
np.unique(Loan_data_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [49]:
np.unique(Loan_data_string[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [50]:
for i in np.unique(Loan_data_string[:,3])[1:]:
    Loan_data_string[:,4]=np.where((Loan_data_string[:,4] == '')& (Loan_data_string[:,3] == i),
                                   i + '5',
                                   Loan_data_string[:,4])

In [51]:
np.unique(Loan_data_string[:,4], return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [52]:
Loan_data_string[:,4] = np.where(Loan_data_string[:,4] == '',
                                   'H1',
                                   Loan_data_string[:,4])

In [53]:
np.unique(Loan_data_string[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [54]:
Loan_data_string = np.delete(Loan_data_string, 3, axis = 1)

In [55]:
Loan_data_string[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [56]:
head_strings = np.delete(head_strings, 3)

In [57]:
head_strings[3]

'sub_grade'

In [58]:
np.unique(Loan_data_string[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [59]:
keys = list(np.unique(Loan_data_string[:,3]))
values = list(range(1, np.unique(Loan_data_string[:,3]).shape[0] + 1))
dict_sub_grade = dict(zip(keys , values))

In [60]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [61]:
for i in np.unique(Loan_data_string[:,3]):
    Loan_data_string[:,3] = np.where(Loan_data_string[:,3] == i,
                                    dict_sub_grade[i],
                                    Loan_data_string[:,3]) 


In [62]:
np.unique(Loan_data_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [63]:
head_strings

array(['issue_d', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [64]:
np.unique(Loan_data_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [65]:
Loan_data_string[:,4] = np.where((Loan_data_string[:,4] == '') | (Loan_data_string[:,4] == 'not verified'), 0,1)

In [66]:
np.unique(Loan_data_string[:,4])

array(['0', '1'], dtype='<U69')

In [67]:
Loan_data_string[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [68]:
np.chararray.strip(Loan_data_string[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [69]:
Loan_data_string[:,5] = np.chararray.strip(Loan_data_string[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [70]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [71]:
Loan_data_numeric[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [72]:
Loan_data_string[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [73]:
np.array_equal(Loan_data_numeric[:,0].astype(dtype = np.int32), Loan_data_string[:,5].astype(dtype = np.int32))

True

In [74]:
Loan_data_string = np.delete(Loan_data_string, 5, axis = 1)
head_strings = np.delete(head_strings, 5)

In [75]:
Loan_data_string[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [76]:
head_strings

array(['issue_d', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [77]:
head_strings[5] = "state_address"

In [78]:
np.unique(Loan_data_string[:,5], return_counts = True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [79]:
states_names, states_count = np.unique(Loan_data_string[:,5], return_counts = True)
states_count_sorted = np.argsort(-states_count)
states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [80]:
Loan_data_string[:,5] = np.where(Loan_data_string[:,5] == '',
                                0,
                                Loan_data_string[:,5]) 

In [81]:
states_west = np.array(['WA','OR','CA','NV','ID','MT','WY','UT','CO','AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [82]:
Loan_data_string[:,5] = np.where(np.isin(Loan_data_string[:,5],states_west), 1 ,Loan_data_string[:,5])
Loan_data_string[:,5] = np.where(np.isin(Loan_data_string[:,5],states_south), 2 ,Loan_data_string[:,5])
Loan_data_string[:,5] = np.where(np.isin(Loan_data_string[:,5],states_midwest), 3 ,Loan_data_string[:,5])
Loan_data_string[:,5] = np.where(np.isin(Loan_data_string[:,5],states_east), 4 ,Loan_data_string[:,5])

In [83]:
np.unique(Loan_data_string[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [84]:
Loan_data_string

array([['5', '1', '36 ', '13', '1', '1'],
       ['0', '1', '36 ', '5', '1', '4'],
       ['9', '1', '36 ', '10', '1', '4'],
       ...,
       ['6', '1', '36 ', '5', '1', '1'],
       ['4', '1', '36 ', '17', '1', '3'],
       ['12', '1', '36 ', '4', '0', '3']], dtype='<U69')

In [85]:
Loan_data_string = Loan_data_string.astype(np.int)

C:\Users\Admin\AppData\Local\Temp\ipykernel_9236\2600081224.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Loan_data_string = Loan_data_string.astype(np.int)


In [86]:
Loan_data_string

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [87]:
checkpoint_strings = checkpoint("checkpoint-strings",head_strings, Loan_data_string)


In [88]:
checkpoint_strings["header"]

array(['issue_d', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [89]:
checkpoint_strings["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [90]:
np.array_equal(checkpoint_strings['data'], Loan_data_string)

True

In [92]:
Loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [93]:
np.isnan(Loan_data_numeric).sum()

0

In [97]:
head_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [98]:
temporary_fill

68616520.0

In [100]:
np.isin(Loan_data_numeric[:,0], temporary_fill)

array([False, False, False, ..., False, False, False])

In [101]:
np.isin(Loan_data_numeric[:,0], temporary_fill).sum()

0

In [102]:
head_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [105]:
temporary_stats[:, column_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [106]:
Loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [108]:
Loan_data_numeric[:,2] = np.where(Loan_data_numeric[:,2] == temporary_fill,
                                 temporary_stats[0, column_numeric[2]],
                                 Loan_data_numeric[:,2])
Loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [109]:
temporary_stats[0,column_numeric[3]]

6.0

In [110]:
head_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [113]:
for i in [1,3,4,5]:
    Loan_data_numeric[:,i] = np.where(Loan_data_numeric[:,i] == temporary_fill,
                                     temporary_stats[2,column_numeric[i]],
                                     Loan_data_numeric[:,i])

In [114]:
Loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

In [122]:
EUR_USD = np.genfromtxt("EUR-USD.csv",delimiter = ',', autostrip = True, skip_header = 1, usecols = 3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [124]:
Loan_data_string[:, 0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [126]:
exchange_rate = Loan_data_string[:,0]

for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                            EUR_USD[i-1],
                            exchange_rate)
    
exchange_rate = np.where(exchange_rate == 0,
                        np.mean(EUR_USD),
                        exchange_rate)

exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [128]:
exchange_rate.shape

(10000,)

In [129]:
Loan_data_numeric.shape

(10000, 6)

In [130]:
exchange_rate = np.reshape(exchange_rate, (10000, 1))

In [132]:
Loan_data_numeric = np.hstack((Loan_data_numeric, exchange_rate))

In [136]:
head_numeric = np.concatenate((head_numeric, np.array(['exchange_rate'])))
head_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [137]:
columns_dollar = np.array([1,2,4,5])

In [138]:
Loan_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [140]:
for i in columns_dollar:
    Loan_data_numeric = np.hstack((Loan_data_numeric, np.reshape(Loan_data_numeric[:,i] / Loan_data_numeric[:,6], (10000,1))))

In [141]:
Loan_data_numeric.shape

(10000, 11)

In [142]:
Loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [143]:
header_additional = np.array([column_name + 'EUR' for column_name in head_numeric[columns_dollar]])

In [144]:
header_additional

array(['loan_amntEUR', 'funded_amntEUR', 'installmentEUR', 'total_pymntEUR'], dtype='<U14')

In [146]:
head_numeric = np.concatenate((head_numeric, header_additional))

In [147]:
head_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amntEUR', 'funded_amntEUR', 'installmentEUR', 'total_pymntEUR'], dtype='<U19')

In [149]:
head_numeric[columns_dollar] = np.array([column_name + 'EUR' for column_name in head_numeric[columns_dollar]])

In [150]:
head_numeric

array(['id', 'loan_amntEUR', 'funded_amntEUR', 'int_rate', 'installmentEUR', 'total_pymntEUR',
       'exchange_rate', 'loan_amntEUR', 'funded_amntEUR', 'installmentEUR', 'total_pymntEUR'],
      dtype='<U19')

In [151]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [152]:
head_numeric = head_numeric[columns_index_order]

In [153]:
Loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [154]:
Loan_data_numeric = Loan_data_numeric[:, columns_index_order]

In [155]:
head_numeric

array(['id', 'loan_amntEUR', 'loan_amntEUR', 'funded_amntEUR', 'funded_amntEUR', 'int_rate',
       'installmentEUR', 'installmentEUR', 'total_pymntEUR', 'total_pymntEUR', 'exchange_rate'],
      dtype='<U19')

In [156]:
Loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [157]:
Loan_data_numeric[:,5] = Loan_data_numeric[:,5]/100

In [158]:
Loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

In [160]:
checkpoint_numeric = checkpoint("checkpoint-Numeric", head_numeric, Loan_data_numeric)

In [161]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amntEUR', 'loan_amntEUR', 'funded_amntEUR', 'funded_amntEUR', 'int_rate',
        'installmentEUR', 'installmentEUR', 'total_pymntEUR', 'total_pymntEUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

In [162]:
checkpoint_strings['data'].shape

(10000, 6)

In [163]:
checkpoint_numeric['data'].shape

(10000, 11)

In [165]:
loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_strings['data']))

In [166]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [167]:
np.isnan(loan_data).sum()

0

In [171]:
header_full = np.concatenate((checkpoint_numeric['header'], checkpoint_strings['header']))

In [174]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [175]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        1.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        1.  ,        2.  ]])

In [176]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

In [177]:
loan_data = np.vstack((header_full, loan_data))

In [178]:
np.savetxt("loan-data-preprocessed.csv", 
           loan_data, 
           fmt = "%s", 
           delimiter = ',')